### ISSUE TITLE
Solutions Page

### ISSUE THREAD

**Issue by sharonstolt** [stolt45/Arcana-Jekyll-Theme#12]
We use focused problem solving to design results-oriented learning experiences that allow you to achieve competitive results.
Explore our sample programs below.

Contact us <link to that page> to learn more or to request a quote.

Professional Acumen
Productivity > Time Management | Meetings Management
Innovation > Creativity | Brainstorming | Design Thinking
Career Development > Managing Your Career | Writing Your Development Plan | Informational Interviewing
Communication > Communication Styles | Difficult Conversations | Influencing without Authority

Management & Leadership
Leadership Styles >  StrengthsFinder | HRDQ What’s My Leadership Style
Foundations of Management >  Communication | Feedback | Coaching | Delegation
Leadership Excellence > Leading People | Strategic Planning | Employee Career Development

Custom Solutions
Team Building
New Leader Assimilation
Train-the-Trainer

**Comment by sharonstolt** [comment]
![professionalacumen](https://cloud.githubusercontent.com/assets/18487530/15993988/9c7d1602-30ab-11e6-83c0-90ab38ff717d.png)
![mgmt leadership](https://cloud.githubusercontent.com/assets/18487530/15993994/bd02c048-30ab-11e6-8901-f25fc5348344.png)
![custom solutions](https://cloud.githubusercontent.com/assets/18487530/15993995/c105af7a-30ab-11e6-8438-f98b247d41cd.png)

**Comment by stolt45** [comment]
Resolved by #11
