### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by sharonstolt** [stolt45/Arcana-Jekyll-Theme#14]
Contact information
phone number: (415) 735-4809
email address: sharon@stolt.us.com
website: http://www.stolt.us.com
twitter: @SharonStolt

Contact form fields [can you route that to sharon@stolt.us.com?]

Name
Organization
Phone Number
Email address
How can we help you?  

Sidebar image for right side of page attached.
![contact page sidebar image](https://cloud.githubusercontent.com/assets/18487530/15994896/49eef878-30c5-11e6-8d38-afdea744b311.png)

**Comment by sharonstolt** [comment]
Alternate sidebar image no calendar link.
![1](https://cloud.githubusercontent.com/assets/18487530/15995485/f21ff4ba-30d0-11e6-87e6-ef78e9b6e3c4.png)

**Comment by stolt45** [comment]
Resolved by #11
