### ISSUE TITLE
Header Color

### ISSUE THREAD

**Issue by stolt45** [stolt45/Arcana-Jekyll-Theme#2]
change the color of the header bar to something that blends with the picture

**Comment by sharonstolt** [comment]
#566e8f - mostly desaturated dark blue (from the ocean)
complementary color schemes for this blue: http://www.colorhexa.com/566e8f

#a95c34 - dark moderate orange  (brown from the sand)
complementary color schemes: http://www.colorhexa.com/a95c34

#b44f51 - moderate red (from the bridge)
complementary color schemes: http://www.colorhexa.com/b44f51

#8b4334 - dark moderate red (darker brown from the sand)
complementary color schemes: http://www.colorhexa.com/8b4334

#556a8b - mostly desaturated dark blue - a little deeper than the first one (from the ocean)
complementary color schemes: http://www.colorhexa.com/556a8b

**Comment by stolt45** [comment]
Resolved by PR #7
