### ISSUE TITLE
Hide 2 page links at top?

### ISSUE THREAD

**Issue by sharonstolt** [stolt45/Arcana-Jekyll-Theme#8]
Can you hide the Blog and the Clients page links at the top?  I think it will take longer for me to get those up and running.  Might need to hide Portfolio too until I can get something up there.

**Comment by stolt45** [comment]
@sharonstolt sure, just tell me which titles you want along the top and I'll take out the rest.

**Comment by sharonstolt** [comment]
ok, I want: About, Solutions, Portfolio, and Contact.
Can you also remove the drop down menu for About?

Sharon Stolt
+1 503.929.8539
sharon.stolt@gmail.com
https://www.linkedin.com/in/sharonstolt

**Comment by stolt45** [comment]
Resolved by PR #7
