### ISSUE TITLE
About Page: Bio

### ISSUE THREAD

**Issue by sharonstolt** [stolt45/Arcana-Jekyll-Theme#9]
Add Sharon's Bio & photo to About Page - use the Left Sidebar layout (like currently used on the Solutions page) and put this in the left sidebar portion.

Sharon Stolt
Principal Consultant

Sharon has been designing and delivering results-oriented development programs since 2002.  Part educator, part motivational speaker, Sharon designs and delivers learning experiences that teach new knowledge and skills and inspire the behavior change needed for success.

The first training session Sharon led was prompted by her goal to reduce Aramark Educational Services’ (AER’s) $2M in potential missed Work Opportunity Tax Credit.  She negotiated 15 minutes on the agenda at the company’s new manager orientation; her talk was the only thing standing between the managers and their flight home after a long week of training.  Walking into the room, she threw thousands of play dollars into the air and proceeded to give a compelling presentation on how each manager could recoup the WOTC to his or her bottom line. Over the next 12 months, AER’s potential missed tax credit dropped to less than $1M, and Sharon earned her reputation for bringing an unexpected twist to otherwise dry training topics.

Before she founded Stolt Consulting in 2016, Sharon was Director of Learning & Development at Visa, Inc., where she developed and launched the company’s first comprehensive manager training program, The Visa Manager Experience.  In 2013, Sharon was awarded Visa’s highest honor, the annual Go Beyond Award, as a result of her work on the program.  From 2015-2016, Sharon led the design and launch of the inaugural Visa University campus in Foster City, CA.

Sharon is passionate about causes that benefit her local community and increase educational and development opportunities for historically underrepresented groups.  She volunteers weekly in a special education classroom at King Child Development Center through the Berkeley Schools Fund.

Sharon lives in Berkeley with her husband, Chris, their dog, Bailey, and their extensive collection of California wines. Sharon enjoys experimenting with new recipes and exploring hiking trails, and has been conducting rigorous taste-testing for the best cupcake in the Bay Area for nearly 6 years.

![img_1213](https://cloud.githubusercontent.com/assets/18487530/15988058/7d663f32-2ff7-11e6-9f79-95d04da04919.JPG)

**Comment by stolt45** [comment]
Resolved in #11
